// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NginxCacheFileReader;

#nullable disable

namespace NginxCacheFileReader.Migrations
{
    [DbContext(typeof(NginxCacheContext))]
    [Migration("20251029090022_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("NginxCacheFileReader.CacheItem", b =>
                {
                    b.Property<int>("CacheItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("cache_item_id");

                    b.Property<string>("BodyFileSignatureAscii")
                        .HasColumnType("TEXT")
                        .HasColumnName("body_file_signature_ascii");

                    b.Property<string>("BodyFileSignatureHex")
                        .HasColumnType("TEXT")
                        .HasColumnName("body_file_signature_hex");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_code");

                    b.HasKey("CacheItemId")
                        .HasName("pk_cache_items");

                    b.ToTable("cache_items", (string)null);
                });

            modelBuilder.Entity("NginxCacheFileReader.CacheItemHeader", b =>
                {
                    b.Property<int>("CacheItemHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("cache_item_header_id");

                    b.Property<int>("CacheItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cache_item_id");

                    b.Property<int?>("Crc32")
                        .HasColumnType("INTEGER")
                        .HasColumnName("crc32");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<DateTime?>("ErrorSec")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_sec");

                    b.Property<string>("Etag")
                        .HasColumnType("TEXT")
                        .HasColumnName("etag");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified");

                    b.Property<DateTime?>("UpdatingSec")
                        .HasColumnType("TEXT")
                        .HasColumnName("updating_sec");

                    b.Property<long?>("ValidMsec")
                        .HasColumnType("INTEGER")
                        .HasColumnName("valid_msec");

                    b.Property<DateTime?>("ValidSec")
                        .HasColumnType("TEXT")
                        .HasColumnName("valid_sec");

                    b.Property<string>("Variant")
                        .HasColumnType("TEXT")
                        .HasColumnName("variant");

                    b.Property<string>("Vary")
                        .HasColumnType("TEXT")
                        .HasColumnName("vary");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("CacheItemHeaderId")
                        .HasName("pk_cache_item_header");

                    b.ToTable("cache_item_header", (string)null);
                });

            modelBuilder.Entity("NginxCacheFileReader.HttpHeader", b =>
                {
                    b.Property<int>("HttpHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("http_header_id");

                    b.Property<int>("CacheItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cache_item_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("HttpHeaderId")
                        .HasName("pk_http_header");

                    b.ToTable("http_header", (string)null);
                });

            modelBuilder.Entity("NginxCacheFileReader.CacheItemHeader", b =>
                {
                    b.HasOne("NginxCacheFileReader.CacheItem", "CacheItem")
                        .WithOne("CacheItemHeader")
                        .HasForeignKey("NginxCacheFileReader.CacheItemHeader", "CacheItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cache_item_header_cache_items_cache_item_id");

                    b.Navigation("CacheItem");
                });

            modelBuilder.Entity("NginxCacheFileReader.HttpHeader", b =>
                {
                    b.HasOne("NginxCacheFileReader.CacheItem", "CacheItem")
                        .WithMany("HttpHeaders")
                        .HasForeignKey("CacheItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_http_header_cache_items_cache_item_id");

                    b.Navigation("CacheItem");
                });

            modelBuilder.Entity("NginxCacheFileReader.CacheItem", b =>
                {
                    b.Navigation("CacheItemHeader")
                        .IsRequired();

                    b.Navigation("HttpHeaders");
                });
#pragma warning restore 612, 618
        }
    }
}
